### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by harikt** [allejo/resource-watcher#2]
Hi, 

Can you do some releases for this repo ? So we don't need to point to dev-master which is harmful.

**Comment by allejo** [comment]
Guess I'll get started with [1.0.0](https://github.com/allejo/resource-watcher/releases/tag/v1.0.0)!

**Comment by harikt** [comment]
@allejo did you released earlier ? I didn't noticed it on releases page earlier . Sorry about that.

**Comment by allejo** [comment]
Oh no, I had been meaning to start tagging releases (#1), I just never found an apt time. I tagged 1.0.0 shortly after you created this issue and I realized other people could be using this fork besides me 👍

**Comment by harikt** [comment]
cool.

Thank you.

Did you by the way asked the upstream if they are interested in the same ? 

In that case probably bug fixes and all may be much easier. Thoughts ?

**Comment by allejo** [comment]
By upstream do you mean the original project I forked this from? That project uses the Laravel filesystem object while I changed this project to use Symfony's. The only change I've made here besides the filesystem object is that you can define your own iterator. The original project hasn't be touched since 2015 and [the last 2 PRs to the project](https://github.com/jasonlewis/resource-watcher/pulls) have gone untouched since they were created.

**Comment by harikt** [comment]
> By upstream do you mean the original project I forked this from?

Yes.

> That project uses the Laravel filesystem object while I changed this project to use Symfony's.

I thought illuminate filesystem was using symfony/filesystem under the hood.

Sorry for the confusion.

Thank you for your good work.

**Comment by allejo** [comment]
It does use Symfony's Finder object under the hood and works fundamentally identical but it's still a separate package and I didn't want to have that as an additional dependency and two separate objects when I already had Symfony's version included in my project, which led to this fork 😄
